# Generated by Django 4.1.4 on 2022-12-21 09:38

import card.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_series', models.CharField(max_length=4, verbose_name='Серия карты')),
                ('card_number', models.BigIntegerField(unique=True, verbose_name='Номер карты')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выпуска')),
                ('end_activity_date', models.DateTimeField(default=card.models.get_default_end_activity_date, verbose_name='Дата окончания активности')),
                ('use_date', models.DateTimeField(auto_now=True, verbose_name='Дата использования')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('not_activated', 'Не активирована'), ('activated', 'Активирована'), ('expired', 'Просрочена')], default='not_activated', max_length=15)),
            ],
            options={
                'verbose_name': 'Карту',
                'verbose_name_plural': 'Карты',
            },
        ),
    ]
